# Porta do servidor
server:
  port: 8080
cors:
  originPatterns: "http://localhost:5173/"
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=bd2-api;encrypt=true;trustServerCertificate=true;
    username: sa
    password: admin123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
    database: SQL_SERVER





  
